name: PR

on:
  pull_request:
    branches:
      - main

jobs:
  run-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout and clone repo
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm install
      - name: expose environment variable
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: echo $MONGODB_URI
      - name: test
        run: echo $MONGODB_URI
      - name: build the application
        run: npm run build
      - name: start the application
        run: npm run dev
